/*
Write the shortest program that prints the entire lyrics of "Never Gonna Give You Up" by Rick Astley.

Rules:

Must output the lyrics exactly as they appear in the above pastebin. Here's the raw dump: http://pastebin.com/raw/wwvdjvEj
Cannot rely on any external resources - all lyrics must be generated by / embedded in code.
No use of existing compression algorithms (e.g. gzip / bzipè) unless you include the full algorithm in your code.
Use any language, shortest code wins.
Update, 1st Juneè01è:
For solutions containing non-ASCII text, the size of your solution will be counted in bytes, based on UTF-8 encoding. If you use codepoints that cannot be encoded in UTF-8, your solution will not be judged as valid.

Update, 7th Juneè01è:
Thank you all for your awesome solutions! I'll be accepting the shortest answer tomorrow afternoon. Right now, Peter Taylor's GolfScript answer is winning, so get cracking on some improvements if you want to beat him! :)
*/
var resp = """We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

We've known each other for so long
Your heart's been aching but
You're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it
And if you ask me how I'm feeling
Don't tell me you're too blind to see

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

(Ooh, give you up)
(Ooh, give you up)
(Ooh)
Never gonna give, never gonna give
(Give you up)
(Ooh)
Never gonna give, never gonna give
(Give you up)

We've known each other for so long
Your heart's been aching but
You're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it

I just wanna tell you how I'm feeling
Gotta make you understand

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
""";

F(){var e=' give',a='ever gonna',l=" how I'm feeling",h=' you',i='(Give$h up)\n',j=' tell',k='(Ooh)\nN$a$e, n$a$e\n$i',b="""
N$a$e$h up
N$a let$h down
N$a run around and desert$h
N$a make$h cry
N$a say goodbye
N$a$j a lie and hurt$h

""",c="""
We've known each other for so long
Your heart's been aching but
You're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it""",d="(Ooh,$e$h up)",f='I just wanna$j$h$l\nGotta make$h understand\n';return"""We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
$f
$b$c
And if$h ask me$l
Don't$j me$h're too blind to see

$b$b$d$d$k$k
$c

$f
$b$b$b""".trim();}

H(){var m=' know the',e=' give',a='ever gonna',l=" how I'm feeling",h=' you',i='(Give$h up)\n',j=' tell',k='(Ooh)\nN$a$e, n$a$e\n$i',b="""
N$a$e$h up
N$a let$h down
N$a run around and desert$h
N$a make$h cry
N$a say goodbye
N$a$j a lie and hurt$h

""",c="""
We've known each other for so long
Your heart's been aching but
You're too shy to say it
Inside we both know what's been going on
We$m game and we're gonna play it""",d="(Ooh,$e$h up)",f='I just wanna$j$h$l\nGotta make$h understand\n';return"""We're no strangers to love
You$m rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
$f
$b$c
And if$h ask me$l
Don't$j me$h're too blind to see

$b$b$d$d$k$k
$c

$f
$b$b$b""".trim();}

G(){var s="""We're no strangers-o love
You é-he rules&so do I
A full commitment's what I'm-hinking of
You wouldn't get-his from any other guy
#àè¤
*
0µA9 ifè ask me¤
Don'tà meè're-oo bli9-o see

00ù, g§
ù, g§
£
£

µ
#àè¤
*
000""";Map.from({'0':"""
N!giveè up
N!letè down
N!run arou9&desertè
N!makeè cry
N!say goodbye
N!à a lie&hurtè

""",'£':'ù)\nN!give, n!give\n(G§','§':'iveè up)','*':'%è u9ersta9\n','à':'-ell','!':'ever gonna ','µ':"""
We've én each other for so long
Your heart's been aching but
You're-oo shy-o say it
Inside we both é what's been going on
We é-he game&we're gonna play it
""",'#':'I just wanna','&':' a9 ','é':'know','9':'nd','¤':" how I'm feeling",'è':' you','-':' t','ù':'(Ooh','%':'Gotta make'}).forEach((k,v){s=s.replaceAll(k,v);});return s.trim();}

check(){

}